### PR TITLE
updated plot syntax to function with new and old sns versions

### PR DESCRIPTION
**Pull request by anmorgan24**
As of Seaborn 0.12.0, the plot function only accepts "data" as the first parameter or "x=" and "y=". Any other syntax will throw an error. Because the "x=" and "y=" syntax also works with older versions, I updated the code to support all sns versions

### CODE REVIEW

**Review by frankfletcher — APPROVED** [review]
lgtm

**Comment by frankfletcher** [comment]
I think this notebook is downloaded directly from the web page and not cloned from github, so we'll need to have the team at SB merge it into the curriculum.

Not merging it directly here as this extra step needs to be taken.  @andrewm4894 ?

**Comment by andrewm4894** [comment]
I think we can merge and then just follow up with them to update the student facing zip.

**Comment by andrewm4894** [comment]
We should update this PR to also update the .zip file 

I know it's crazy :) 

But we need update the .ipynb and the recreate the .zip so that it's updated to include the updated notebook. 

That way we can just deliver them the GitHub link to the .zip 

We should also then update the dsc_solutions version of the notebook too in a separate PR

**Comment by andrewm4894** [comment]
So would need separate PR to update the solutions version of notebook in here https://github.com/springboard-curriculum/dsc_solutions/tree/main/Unit%2018%20-%20Machine%20Learning%20Applications/18.2%20Model%20Optimization/18.2.4%20-%20Grid%20Search%20in%20KNN

**Comment by andrewm4894** [comment]
We could actually build a little GitHub action maybe to recreate the zip file on each merge maybe based on some manifest type file or something.

Alternatively as part of updating the curriculum with this fix we could also ask them to update the instructions to just point at this folder in the repo but not quite sure if we ready or there yet. 

See what you guys think.

Minimal is steps above with zip etc and then springboard just grab the .zip file from the repo, perhaps can even use the GitHub raw download link for it, even that would be better actually. 

Or we figure out foolproof instructions to also update the curriculum FE to point students directly at the notebook. Note this one is not quite standalone since has a /data folder so hard to fully do in a colab too.

**Review by andrewm4894 — CHANGES_REQUESTED** [review]
Think we should update the .zip too and link to sibling PR in solutions repo

**Comment by anmorgan24** [comment]
I updated the zip file in the dsc repo. I also created an issue so that I could link the PRs for the dsc repo and dsc-solutions repo, but am realizing now that I don't have permission to fork the dsc-solutions repo. Is there another way I can submit a PR for that repo?

**Comment by andrewm4894** [comment]
Added team as maintainer rile.on the solutions repo so hopefully should be able to make a PR in there now

**Comment by anmorgan24** [comment]
Hmm... I'm still seeing this message ("Cannot fork because forking is disabled"). Any ideas?
Screen Shot 2022-12-17 at 2 11 09 PM

**Comment by andrewm4894** [comment]
See if you can just make a branch and work in there.

**Comment by anmorgan24** [comment]
Done :)

**Review by andrewm4894 — APPROVED** [review]

**Comment by andrewm4894** [comment]
Cross linking the related commit in solutions

https://github.com/springboard-curriculum/dsc_solutions/commit/7fd8da178ccd7720906c1ed40fc679773a553945

**Comment by andrewm4894** [comment]
> Hmm... I'm still seeing this message ("Cannot fork because forking is disabled"). Any ideas? Screen Shot 2022-12-17 at 2 11 09 PM

I think forking might be disabled by default because the repo is private maybe. Think is fine to leave like that so all work related to it has to live on branches in that repo, think that's the idea of the GitHub defaults here.

**Comment by anmorgan24** [comment]
Thanks for all your help Andrew and Frank!

**Pull request merged**
